### PR TITLE
Added support for a custom menuClass

### PR DESCRIPTION
**Pull request by daevid66**
Hi, here is a suggestion on how to solve the custom menu class feature.

### CODE REVIEW

**Comment by daevid66** [comment]
Hi again, what is the procedure if you accept my pull request, will a new version be released quite soon or may it take a while (days/weeks)? Not meaning to put stress on you, just need to know to plan my current project that needs this feature.

Cheers,

David

**Comment by isaacplmann** [comment]
I plan to review your PR and release today or tomorrow.

**Comment by isaacplmann** [comment]
Looks good.  I update the styles in your example, but the implementation works.

If you add some documentation in the readme, I'll merge this in.  Something short like the AutoFocus section should be sufficient.

Thanks!

**Comment by daevid66** [comment]
Added instructions to the readme. Thanks for fixing the style issue...

**Comment by isaacplmann** [comment]
Thanks! I'll get a release out today.

**Pull request merged**
